apiVersion: v1
kind: Service  
metadata:  
  name: tbl-service  
  labels:  
    name: tbl-service  
spec:
  type: NodePort  
  ports:  
  - port: 8080
    targetPort: 8080 
    protocol: TCP
    nodePort: 8556
  selector:  
    name: tbl-pod
